---
- name: Configure Rsyslog to Forward Logs Over TCP
  hosts: all
  become: yes
  tasks:

    - name: Ensure rsyslog is installed
      package:
        name: rsyslog
        state: present

    - name: Configure rsyslog to forward logs over TCP
      lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @@{{ log_server }}:514"
        insertafter: EOF
        state: present

    - name: Restart rsyslog service
      service:
        name: rsyslog
        state: restarted


